### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by McFranko** [tari-project/randomx-rs#30]
I have seen a pull request adding docs, but I can't find a link to any documentation for this. Does it not exist, or have I just not found it?

**Comment by delta1** [comment]
Hi @McFranko - if you are referring to #19 then the docs are commented in [lib.rs](https://github.com/tari-project/randomx-rs/blob/development/src/lib.rs#L49). But I do think "how to use this library" docs are a great idea!

**Comment by McFranko** [comment]
For some reason there isn't a docs.rs entry. I can't check right now, but if the `cargo docs` command doesn't work, then that's probably why

**Comment by delta1** [comment]
Thanks for the feedback, that's a good idea.

**Comment by delta1** [comment]
`cargo doc` does work, although the documentation could definitely be improved.

**Comment by McFranko** [comment]
Would you have any idea why this project doesn't show up on docs.rs?

**Comment by delta1** [comment]
So it looks like the build fails on docs.rs, which is why it isn't published: https://docs.rs/crate/randomx-rs/0.5.0

Here is the build failure: https://docs.rs/crate/randomx-rs/0.5.0/builds/340655 

It seems that `build.rs` is trying to clone the RandomX repo - but builds on docs.rs don't have network access. 

I'm not sure if this can be resolved, your best bet is probably just to clone the repo and run `cargo doc` locally, sorry!

**Comment by delta1** [comment]
Resolved in #32 

https://docs.rs/randomx-rs/1.1.9/randomx_rs/
